name: conflict_model

channels:
  - conda-forge

dependencies:
  - python>=3.6
  - geopandas==0.8.0
  - xarray==0.15.1
  - pandas==1.0.3
  - numpy==1.18.1
  - matplotlib==3.2.1
  - rasterio==1.1.0
  - pytest>=5.4.2
  - pytest-runner
  - descartes
  - rioxarray
  - ipython
  - notebook
  - nbconvert
  - scikit-learn
  - netcdf4
  - ConfigParser
  - click
  - seaborn
  - pip
  - pip:
    - rasterstats==0.14.0
    