name: copro

channels:
  - conda-forge

dependencies:
  - python==3.9.18
  - xarray==2023.12.0
  - pandas==2.1.4
  - numpy==1.26.3
  - rtree==1.1.0
  - pytest==7.4.4
  - pytest-runner==6.0.0
  - descartes==1.1.0
  - rioxarray==0.15.0
  - ipython==8.18.1
  - notebook==7.0.6
  - nbconvert==7.14.1
  - ipykernel==6.28.0
  - scikit-learn==1.3.2
  - netcdf4==1.6.0
  - ConfigParser==5.3.0
  - click==8.1.7
  - seaborn==0.13.1
  - colorama==0.4.6
  - setuptools==69.0.3
  - pillow==8.1.0
  - geopandas==0.14.2
  - rasterio==1.2.10
  - rasterstats==0.19.0
    
